#!/bin/bash
cd /home/ostlund/WWW/thermiq-docker/mqtt
source env/bin/activate
echo `which python`
export USERNAME=thermiq
export PASSWORD=lissner
export ROOM=16
export HOTWSTART=35
export HOTWSTOP=50
export REDUCTION=0
python set_registers.py  
