#!/bin/bash
cd /home/ostlund/WWW/thermiq-docker/mqtt
source env/bin/activate
echo `which python`
export USERNAME=thermiq
export PASSWORD=lissner
export ROOM=20
export HOTWSTART=50
export HOTWSTOP=60
export REDUCTION=0

python set_registers.py  
